TYPE=VIEW
query=select `utsyusril`.`mahasiswa`.`id` AS `id`,`utsyusril`.`mahasiswa`.`nim` AS `nim`,`utsyusril`.`mahasiswa`.`nama_mhs` AS `nama_mhs`,`utsyusril`.`mahasiswa`.`jenis_kelamin` AS `jenis_kelamin`,`utsyusril`.`mahasiswa`.`alamat` AS `alamat`,`utsyusril`.`mahasiswa`.`no_hp` AS `no_hp` from `utsyusril`.`mahasiswa`
md5=c5784a11e8578cff534427fc6c32f2e7
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2019-11-11 22:30:59
create-version=2
source=SELECT * FROM mahasiswa;
client_cs_name=cp850
connection_cl_name=cp850_general_ci
view_body_utf8=select `utsyusril`.`mahasiswa`.`id` AS `id`,`utsyusril`.`mahasiswa`.`nim` AS `nim`,`utsyusril`.`mahasiswa`.`nama_mhs` AS `nama_mhs`,`utsyusril`.`mahasiswa`.`jenis_kelamin` AS `jenis_kelamin`,`utsyusril`.`mahasiswa`.`alamat` AS `alamat`,`utsyusril`.`mahasiswa`.`no_hp` AS `no_hp` from `utsyusril`.`mahasiswa`
mariadb-version=100128
